image:
  - Visual Studio 2019

platform:
  - x64

build_script:
  - cmd: >-
      cd test

      msbuild.exe test.sln /verbosity:minimal /t:Build /p:Configuration=Release;Platform=%PLATFORM%

test_script:
  - cmd: x64\Release\test.exe
